openapi: 3.0.4
info:
  title: MatuleApp
  description: |-
    Приложение matule
  termsOfService: https://www.back4app.com/terms-of-service.pdf
  contact:
    email: hello@world.ru
  version: 1.0.00
servers:
  - url: https://api.matule.ru/api
tags:
  - name: user
    description: Действия с пользователем
  - name: shop
    description: Действия с магазином
  - name: project
    description: Действия с проектами
  - name: backet
    description: Действия с корзиной
  - name: order
    description: Действия с заказом
    

paths:
  /collections/users/records:
    post:
      tags:
        - user
      summary: Регистрация
      operationId: createUser
      requestBody:
        description: Регистрация
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestRegister'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseRegister'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
  /collections/users/records/{id_user}:
    get:
      tags:
        - user
      summary: Получение информации о пользователе
      operationId: user
      parameters:
        - in: path
          name: id_user
          required: true
          schema:
            type: string
          description: ID пользователя
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
    patch:
      tags:
        - user
      summary: Изменение профиля.
      operationId: updateUser
      parameters:
        - in: path
          name: id_user
          required: true
          schema:
            type: string
          description: ID пользователя
      requestBody:
        description: Изменение профиля
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RequestUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
  /collections/users/auth-with-password:
    post:
      tags:
        - user
      summary: Авторизация
      operationId: auth
      requestBody:
        description: Регистрация
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAuth'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseAuth'
        default:
          description: Unexpected error
  /collections/_authOrigins/records:
    get:
      tags:
        - user
      summary: Получение id токена
      operationId: usersAuth
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersAuth'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
  /collections/_authOrigins/records/{id_token}:
    delete:
      tags:
        - user
      summary: Удаление пользователя
      operationId: ProductDelete
      parameters:
        - in: path
          name: id_token
          required: true
          schema:
            type: string
          description: id_token
      responses:
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []


    
    
 
  /collections/news/records:
    get:
      tags:
        - shop
      summary: Акции и новости
      operationId: news
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsesNews'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
  
   
  /collections/products/records:
    get:
      tags:
        - shop
      summary: Список продуктов с поиском
      operationId: listProductSerach
      parameters:
        - in: query
          name: filter
          required: false
          schema:
            type: string
          description: фильтр  
          example: "(title ?~ '1')"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseProducts'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []

  /collections/products/records/{id_product}:
    get:
      tags:
        - shop
      summary: Описание продукта
      operationId: Product
      parameters:
        - in: path
          name: id_product
          required: true
          schema:
            type: string
          description: id_product 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
        
        
  /collections/project/records:
    get:
      tags:
        - project
      summary: Список проектов
      operationId: ListProject
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsesProject'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
    post:
      tags:
        - project
      summary: Создание проекта
      operationId: projectCreate
      requestBody:
        description: Создание проекта
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestProject'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
    
    
  /collections/cart/records:
   post:
      tags:
        - backet
      summary: Создание корзины
      operationId: createBusket
      requestBody:
        description: Создание
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCart'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCart'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
  /collections/cart/records/{id_bucket}:
    patch:
      tags:
        - backet
      summary: Изменение корзины
      operationId: updateUser
      parameters:
        - in: path
          name: id_bucket
          required: true
          schema:
            type: string
          description: id bucket
      requestBody:
        description: Изменение корзины
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RequestCart'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCart'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []
 
  /collections/orders/records:
   post:
      tags:
        - order
      summary: Создание заказа
      operationId: createOrder
      requestBody:
        description: Создание
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestOrder'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOrder'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400'
        default:
          description: Unexpected error
      security:
        - bearerHttpAuthentication: []          
          
components:
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer token using a JWT
      type: http
      scheme: Bearer
  schemas:
    RequestCart:
      type: object
      properties: 
        user_id:
          type: string
        product_id:
          type: string
        count:
          type: integer
    RequestOrder:
      type: object
      properties: 
        user_id:
          type: string
        product_id:
          type: string
        count:
          type: integer
    ResponseCart:
      type: object
      properties: 
        id:
          type: string
        collectionId:
          type: string
        collectionName:
          type: string
        created:
          type: string
        updated:
          type: string
        user_id:
          type: string
        product_id:
          type: string
        count:
          type: integer
    ResponseOrder:
      type: object
      properties: 
        id:
          type: string
        collectionId:
          type: string
        collectionName:
          type: string
        created:
          type: string
        updated:
          type: string
        user_id:
          type: string
        product_id:
          type: string
        count:
          type: integer
    UsersAuth:
      type: object
      properties: 
        page:
          type: integer
          format: integer
        perPage:
          type: integer
          format: integer
        totalPages:
          type: integer
          format: integer
        totalItems:
          type: integer
          format: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/UserAuth'
    UserAuth:
      properties:
        id:
          type: string
        collectionId:
          type: string
        collectionName:
          type: string
        created:
          type: string
        updated:
          type: string      
        collectionRef:
          type: string      
        fingerprint:
          type: string      
        recordRef:
          type: string      
  
    ResponsesProject:
      type: object
      properties: 
        page:
          type: integer
          format: integer
        perPage:
          type: integer
          format: integer
        totalPages:
          type: integer
          format: integer
        totalItems:
          type: integer
          format: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Project'
    Project:
      type: object
      properties:
        id:
          type: string
        collectionId:
          type: string
        collectionName:
          type: string
        created:
          type: string
        updated:
          type: string  
        title:
          type: string  
        dateStart:
          type: string  
        dateEnd:
          type: string  
        gender:
          type: string  
        description_source:
          type: string  
        category:
          type: string  
        image:
          type: string  
        user_id:
          type: string  
    RequestProject:
      type: object
      properties:
        title:
          type: string  
        typeProject:
          type: string  
        user_id:
          type: string  
        dateStart:
          type: string  
        dateEnd:
          type: string  
        gender:
          type: string  
        description_source:
          type: string  
        category:
          type: string  
        image:
          type: string
          format: binary 
    ResponsesNews:
      type: object
      properties: 
        page:
          type: integer
          format: integer
        perPage:
          type: integer
          format: integer
        totalPages:
          type: integer
          format: integer
        totalItems:
          type: integer
          format: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/News'
    
    News:
      type: object
      properties: 
        collectionId:
          type: string
        collectionName:
          type: string
        id:
          type: string
        newsImage: 
            type: string
        created:
            type: string
        updated:
            type: string        
    ResponseProducts:
      type: object
      properties:
        page:
          type: integer
          format: integer
        perPage:
          type: integer
          format: integer
        totalPages:
          type: integer
          format: integer
        totalItems:
          type: integer
          format: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductItem'
    Product:
      type: object
      properties: 
        id:
          type: string
        collectionId:
          type: string
        collectionName:
          type: string
        created:
          type: string
        updated:
          type: string
        title:
          type: string
        description: 
          type: string
        price:
          type: integer
        typeCloses:
          type: string
        type:
          type: string
        approximateCost:
          type: string
    ProductItem:
      type: object
      properties: 
        id:
          type: string
        title:
          type: string
        price:
          type: integer
        typeCloses:
          type: string
        type:
          type: string
    RequestRegister:
      type: object
      properties:
        email:
          type: string
          format: string
          example: 'example@test.ru'
        password:
          type: string
          format: string
        passwordConfirm:
          type: string
          format: string
    ResponseRegister:
      type: object
      properties:
        collectionId:
          type: string
        collectionName:
          type: string
        created:
          type: string
        emailVisibility:
          type: boolean
        firstname:
          type: string
        id:
          type: string
        lastname:
          type: string
        secondname:
          type: string
        updated:
          type: string
        verified:
          type: boolean
        datebirthday:
          type: string
        gender:
          type: string
    RequestAuth:
      type: object
      properties:
        identity:
          type: string
          format: string
          example: 'example@test.ru'
        password:
          type: string
          format: string
    User:
      type: object
      properties:
        collectionId:
          type: string
        collectionName:
          type: string
        created:
          type: string
        emailVisibility:
          type: boolean
        firstname:
          type: string
        id:
          type: string
        lastname:
          type: string
        secondname:
          type: string
        updated:
          type: string
        verified:
          type: boolean
        datebirthday:
          type: string
        gender:
          type: string
    ResponseAuth:
      type: object
      properties:
        record:
          $ref: '#/components/schemas/User'
        token:
          type: string
          format: string
    RequestUser:
      type: object
      properties:
        email:
          type: string
        emailVisibility:
          type: boolean
        firstname:
          type: string
        lastname:
          type: string
        secondname:
          type: string
        datebirthday:
          type: string
        gender: 
          type: string
    Error400:
      type: object
      properties:
        status: 
          type: integer
          example: 400
        message:
          type: string
          example: "Failed to create record."
        data:
          type: object
  
 
   
